const express = require('express');
const puppeteer = require('puppeteer');
const bodyParser = require('body-parser');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 10000;

app.use(bodyParser.json());
app.use(express.static(path.join(__dirname)));

async function generateImageFromPerchance(prompt) {
    let browser;
    try {
        browser = await puppeteer.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-gpu',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080',
                '--no-zygote',
                '--single-process'
            ],
            executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || puppeteer.executablePath(),
        });
        const page = await browser.newPage();
        await page.setUserAgent('Mozilla/5.0 (Linux; Android 13; CPH2205) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36');

        await page.goto('https://perchance.org/ai-image-generator', {
            waitUntil: 'networkidle0',
            timeout: 60000
        });

        let userKey = null;
        let imageId = null;

        // Listener for responses to capture userKey and imageId
        page.on('response', async response => {
            const url = response.url();

            // Intercept POST to /api/generate
            if (url.startsWith('https://image-generation.perchance.org/api/generate') && response.request().method() === 'POST') {
                try {
                    const responseJson = await response.json();
                    if (responseJson && responseJson.imageId) {
                        imageId = responseJson.imageId;
                    } else if (responseJson && responseJson.data && responseJson.data.imageId) {
                        imageId = responseJson.data.imageId;
                    }
                } catch (e) {
                }
            }
            // Capture userKey from any API GET requests (e.g., checkUserVerificationStatus, getUserQueuePosition)
            if (url.startsWith('https://image-generation.perchance.org/api/') && url.includes('userKey=')) {
                const urlParams = new URLSearchParams(url.split('?')[1]);
                const foundUserKey = urlParams.get('userKey');
                if (foundUserKey && !userKey) {
                    userKey = foundUserKey;
                }
            }
        });

        const promptInputSelector = 'textarea.form-control[aria-label="Prompt"]';
        const generateButtonSelector = 'button.btn.btn-primary.submit-button';

        await page.waitForSelector(promptInputSelector, { timeout: 30000 });
        await page.waitForSelector(generateButtonSelector, { timeout: 30000 });

        await page.focus(promptInputSelector);
        await page.keyboard.down('Control');
        await page.keyboard.press('A');
        await page.keyboard.up('Control');
        await page.keyboard.press('Delete');
        await page.type(promptInputSelector, prompt);

        // Instead of clicking the button, we'll manually send the POST request
        // This is because directly clicking might trigger a sequence that's hard to control,
        // and we specifically observed the POST request for generate.
        // We'll need to extract parameters from the client-side JS for the POST payload.
        
        // This part is the most speculative without the exact POST payload structure from DevTools.
        // I will use a plausible structure based on previous GET parameters.
        // If this doesn't work, you'll HAVE to get the full POST payload from DevTools.
        const defaultPayload = {
            "prompt": prompt, // This is dynamic
            "seed": -1, // From previous observations
            "resolution": "768x768", // From previous observations
            "guidanceScale": 7, // From previous observations
            "negativePrompt": "", // From previous observations
            "channel": "ai-text-to-image-generator", // From previous observations
            "subChannel": "public", // From previous observations
            // userKey and requestId usually dynamically generated by client-side JS for POST
            // For now, we'll try to let the page's JS handle it, and capture userKey from GETs.
            // If the POST needs userKey directly in payload, this will fail.
        };

        // Try to trigger the POST request by evaluating script
        // This part is HIGHLY dependent on how Perchance's JS triggers the POST
        // A safer way is to just click the button and let the page JS handle it.
        // Let's revert to clicking the button for robustness, as it seemed to work before.
        // The `page.on('response', ...)` should capture the POST response anyway.
        await page.click(generateButtonSelector);


        let queuePosition = -1;
        let maxRetries = 60;
        let retryCount = 0;

        while (queuePosition !== 0 && retryCount < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, 2000));
            retryCount++;

            if (!userKey) {
                continue;
            }

            try {
                const queueUrl = `https://image-generation.perchance.org/api/getUserQueuePosition?userKey=${userKey}&requestId=${Date.now() + Math.random()}&__cacheBust=${Math.random()}`;
                const queueResponse = await page.evaluate(async (url) => {
                    const response = await fetch(url);
                    return response.json();
                }, queueUrl);

                if (queueResponse && typeof queueResponse.position === 'number') {
                    queuePosition = queueResponse.position;
                } else if (queueResponse && queueResponse.status === 'ready') {
                    queuePosition = 0;
                }
                if (queuePosition === 0 && !imageId && queueResponse && queueResponse.imageId) {
                    imageId = queueResponse.imageId;
                }

            } catch (e) {
            }
        }

        if (queuePosition !== 0 || !imageId) {
            throw new Error("Image generation timed out or could not retrieve image ID.");
        }

        const downloadUrl = `https://image-generation.perchance.org/api/downloadTemporaryImage?imageId=${imageId}`;

        const imageBuffer = await page.evaluate(async (url) => {
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const buffer = await response.arrayBuffer();
            return Array.from(new Uint8Array(buffer));
        }, downloadUrl);

        if (!imageBuffer || imageBuffer.length === 0) {
            throw new Error("Failed to get image data or image is empty.");
        }

        return `data:image/png;base64,${Buffer.from(imageBuffer).toString('base64')}`;

    } catch (error) {
        throw error;
    } finally {
        if (browser) {
            await browser.close();
        }
    }
}

app.post('/generate-image', async (req, res) => {
    const { prompt } = req.body;

    if (!prompt) {
        return res.status(400).json({ error: 'Prompt is required.' });
    }

    try {
        const imageDataUri = await generateImageFromPerchance(prompt);

        if (imageDataUri) {
            res.json({ success: true, imageData: imageDataUri });
        } else {
            res.status(500).json({ success: false, error: 'Image generation failed: No image data returned.' });
        }

    } catch (error) {
        res.status(500).json({ success: false, error: error.message || 'Internal server error during image generation.' });
    }
});

app.listen(PORT, () => {
});
