services:
  - type: web
    name: anime-gen-api
    env: node
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y \
        libnss3 \
        libatk-bridge2.0-0 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libpangocairo-1.0-0 \
        libgtk-3-0 \
        libdrm2 \
        libatspi2.0-0
      npm install
    startCommand: node index.js
